// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// f_ScreenSizeInterval
double f_ScreenSizeInterval(double age, double v_cut, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec v, arma::rowvec v_wts, double d0, double v0);
RcppExport SEXP _BC_f_ScreenSizeInterval(SEXP ageSEXP, SEXP v_cutSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP vSEXP, SEXP v_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v_cut(v_cutSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type v_wts(v_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_ScreenSizeInterval(age, v_cut, scr, par, t, t_wts, v, v_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SymptSizeInterval
double f_SymptSizeInterval(double age, double v_cut, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec v, arma::rowvec v_wts, double d0, double v0);
RcppExport SEXP _BC_f_SymptSizeInterval(SEXP ageSEXP, SEXP v_cutSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP vSEXP, SEXP v_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v_cut(v_cutSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type v_wts(v_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SymptSizeInterval(age, v_cut, scr, par, t, t_wts, v, v_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CaseIntegral
double f_CaseIntegral(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_CaseIntegral(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CaseIntegral(age, v, scr, par, t, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensIntegral
double f_CensIntegral(double age, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensIntegral(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensIntegral(age, scr, par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_ScreenCase
double f_ScreenCase(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_ScreenCase(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_ScreenCase(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SymptCase
double f_SymptCase(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_SymptCase(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SymptCase(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensCase
double f_CensCase(double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensCase(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensCase(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// IndL
double IndL(int is_case, int is_scr, double age, double v, arma::rowvec scr, double entry, arma::rowvec e_scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_IndL(SEXP is_caseSEXP, SEXP is_scrSEXP, SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP entrySEXP, SEXP e_scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type is_case(is_caseSEXP);
    Rcpp::traits::input_parameter< int >::type is_scr(is_scrSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< double >::type entry(entrySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type e_scr(e_scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(IndL(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CaseIntegral_odg
double f_CaseIntegral_odg(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_CaseIntegral_odg(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CaseIntegral_odg(age, v, scr, par, t, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensIntegral_odg
double f_CensIntegral_odg(double age, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensIntegral_odg(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensIntegral_odg(age, scr, par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_ScreenCase_odg
double f_ScreenCase_odg(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_ScreenCase_odg(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_ScreenCase_odg(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SymptCase_odg
double f_SymptCase_odg(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_SymptCase_odg(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SymptCase_odg(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensCase_odg
double f_CensCase_odg(double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensCase_odg(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensCase_odg(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// IndL_odg
double IndL_odg(int is_case, int is_scr, double age, double v, arma::rowvec scr, double entry, arma::rowvec e_scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_IndL_odg(SEXP is_caseSEXP, SEXP is_scrSEXP, SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP entrySEXP, SEXP e_scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type is_case(is_caseSEXP);
    Rcpp::traits::input_parameter< int >::type is_scr(is_scrSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< double >::type entry(entrySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type e_scr(e_scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(IndL_odg(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CaseIntegral2
double f_CaseIntegral2(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_CaseIntegral2(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CaseIntegral2(age, v, scr, par, t, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensIntegral2
double f_CensIntegral2(double age, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensIntegral2(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensIntegral2(age, scr, par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_ScreenCase2
double f_ScreenCase2(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_ScreenCase2(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_ScreenCase2(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SymptCase2
double f_SymptCase2(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_SymptCase2(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SymptCase2(age, v, scr, par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensCase2
double f_CensCase2(double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensCase2(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensCase2(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// IndL2
double IndL2(int is_case, int is_scr, double age, double v, arma::rowvec scr, double entry, arma::rowvec e_scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_IndL2(SEXP is_caseSEXP, SEXP is_scrSEXP, SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP entrySEXP, SEXP e_scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type is_case(is_caseSEXP);
    Rcpp::traits::input_parameter< int >::type is_scr(is_scrSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< double >::type entry(entrySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type e_scr(e_scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(IndL2(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// CondOnset
arma::colvec CondOnset(double age, double v, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_CondOnset(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(CondOnset(age, v, scr, par, t, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_pMVK
arma::colvec f_pMVK(arma::colvec t, double A, double B, double delta);
RcppExport SEXP _BC_f_pMVK(SEXP tSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(f_pMVK(t, A, B, delta));
    return rcpp_result_gen;
END_RCPP
}
// f_dMVK
arma::colvec f_dMVK(arma::colvec t, double A, double B, double delta);
RcppExport SEXP _BC_f_dMVK(SEXP tSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(f_dMVK(t, A, B, delta));
    return rcpp_result_gen;
END_RCPP
}
// RiskOnsetCPF
arma::colvec RiskOnsetCPF(arma::colvec t, double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_RiskOnsetCPF(SEXP tSEXP, SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskOnsetCPF(t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// RiskOnsetPDF
arma::colvec RiskOnsetPDF(arma::colvec t, double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_RiskOnsetPDF(SEXP tSEXP, SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskOnsetPDF(t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// RiskSympt
double RiskSympt(double x, double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_RiskSympt(SEXP xSEXP, SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskSympt(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SensScreen
double f_SensScreen(double x, double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_SensScreen(SEXP xSEXP, SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SensScreen(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// SensScreen
double SensScreen(double x, double age, arma::rowvec scr, arma::vec par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_SensScreen(SEXP xSEXP, SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(SensScreen(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_RiskScreen
double f_RiskScreen(double age, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_RiskScreen(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_RiskScreen(age, scr, par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_RiskScreen_odg
double f_RiskScreen_odg(double age, arma::rowvec scr, arma::vec par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_RiskScreen_odg(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_RiskScreen_odg(age, scr, par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CaseIntegral4
double f_CaseIntegral4(double age, double v, arma::rowvec scr, arma::vec par, arma::rowvec scr_par, arma::colvec t, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_CaseIntegral4(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CaseIntegral4(age, v, scr, par, scr_par, t, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensIntegral4
double f_CensIntegral4(double age, arma::rowvec scr, arma::vec par, arma::rowvec scr_par, arma::colvec t, arma::colvec t_wts, arma::rowvec r, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensIntegral4(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP tSEXP, SEXP t_wtsSEXP, SEXP rSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensIntegral4(age, scr, par, scr_par, t, t_wts, r, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_ScreenCase4
double f_ScreenCase4(double age, double v, arma::rowvec scr, arma::vec par, arma::rowvec scr_par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_ScreenCase4(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_ScreenCase4(age, v, scr, par, scr_par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SymptCase4
double f_SymptCase4(double age, double v, arma::rowvec scr, arma::vec par, arma::rowvec scr_par, arma::colvec t_pts, arma::colvec t_wts, double d0, double v0);
RcppExport SEXP _BC_f_SymptCase4(SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SymptCase4(age, v, scr, par, scr_par, t_pts, t_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_CensCase4
double f_CensCase4(double age, arma::rowvec scr, arma::vec par, arma::rowvec scr_par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_f_CensCase4(SEXP ageSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_CensCase4(age, scr, par, scr_par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// IndL4
double IndL4(int is_case, int is_scr, double age, double v, arma::rowvec scr, double entry, arma::rowvec e_scr, arma::vec par, arma::rowvec scr_par, arma::rowvec e_scr_par, arma::colvec t_pts, arma::colvec t_wts, arma::rowvec r_pts, arma::rowvec r_wts, double d0, double v0);
RcppExport SEXP _BC_IndL4(SEXP is_caseSEXP, SEXP is_scrSEXP, SEXP ageSEXP, SEXP vSEXP, SEXP scrSEXP, SEXP entrySEXP, SEXP e_scrSEXP, SEXP parSEXP, SEXP scr_parSEXP, SEXP e_scr_parSEXP, SEXP t_ptsSEXP, SEXP t_wtsSEXP, SEXP r_ptsSEXP, SEXP r_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type is_case(is_caseSEXP);
    Rcpp::traits::input_parameter< int >::type is_scr(is_scrSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< double >::type entry(entrySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type e_scr(e_scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr_par(scr_parSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type e_scr_par(e_scr_parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_pts(t_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t_wts(t_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_pts(r_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r_wts(r_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(IndL4(is_case, is_scr, age, v, scr, entry, e_scr, par, scr_par, e_scr_par, t_pts, t_wts, r_pts, r_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}
// f_SizeBounded
double f_SizeBounded(double x, double v, double c, double s, arma::rowvec scr, arma::vec par, arma::colvec gk_pts, arma::colvec gk_wts, arma::rowvec gl_pts, arma::rowvec gl_wts, double d0, double v0);
RcppExport SEXP _BC_f_SizeBounded(SEXP xSEXP, SEXP vSEXP, SEXP cSEXP, SEXP sSEXP, SEXP scrSEXP, SEXP parSEXP, SEXP gk_ptsSEXP, SEXP gk_wtsSEXP, SEXP gl_ptsSEXP, SEXP gl_wtsSEXP, SEXP d0SEXP, SEXP v0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type scr(scrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type gk_pts(gk_ptsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type gk_wts(gk_wtsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type gl_pts(gl_ptsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type gl_wts(gl_wtsSEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    rcpp_result_gen = Rcpp::wrap(f_SizeBounded(x, v, c, s, scr, par, gk_pts, gk_wts, gl_pts, gl_wts, d0, v0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BC_f_ScreenSizeInterval", (DL_FUNC) &_BC_f_ScreenSizeInterval, 10},
    {"_BC_f_SymptSizeInterval", (DL_FUNC) &_BC_f_SymptSizeInterval, 10},
    {"_BC_f_CaseIntegral", (DL_FUNC) &_BC_f_CaseIntegral, 8},
    {"_BC_f_CensIntegral", (DL_FUNC) &_BC_f_CensIntegral, 9},
    {"_BC_f_ScreenCase", (DL_FUNC) &_BC_f_ScreenCase, 8},
    {"_BC_f_SymptCase", (DL_FUNC) &_BC_f_SymptCase, 8},
    {"_BC_f_CensCase", (DL_FUNC) &_BC_f_CensCase, 9},
    {"_BC_IndL", (DL_FUNC) &_BC_IndL, 14},
    {"_BC_f_CaseIntegral_odg", (DL_FUNC) &_BC_f_CaseIntegral_odg, 8},
    {"_BC_f_CensIntegral_odg", (DL_FUNC) &_BC_f_CensIntegral_odg, 9},
    {"_BC_f_ScreenCase_odg", (DL_FUNC) &_BC_f_ScreenCase_odg, 8},
    {"_BC_f_SymptCase_odg", (DL_FUNC) &_BC_f_SymptCase_odg, 8},
    {"_BC_f_CensCase_odg", (DL_FUNC) &_BC_f_CensCase_odg, 9},
    {"_BC_IndL_odg", (DL_FUNC) &_BC_IndL_odg, 14},
    {"_BC_f_CaseIntegral2", (DL_FUNC) &_BC_f_CaseIntegral2, 8},
    {"_BC_f_CensIntegral2", (DL_FUNC) &_BC_f_CensIntegral2, 9},
    {"_BC_f_ScreenCase2", (DL_FUNC) &_BC_f_ScreenCase2, 8},
    {"_BC_f_SymptCase2", (DL_FUNC) &_BC_f_SymptCase2, 8},
    {"_BC_f_CensCase2", (DL_FUNC) &_BC_f_CensCase2, 9},
    {"_BC_IndL2", (DL_FUNC) &_BC_IndL2, 14},
    {"_BC_CondOnset", (DL_FUNC) &_BC_CondOnset, 8},
    {"_BC_f_pMVK", (DL_FUNC) &_BC_f_pMVK, 4},
    {"_BC_f_dMVK", (DL_FUNC) &_BC_f_dMVK, 4},
    {"_BC_RiskOnsetCPF", (DL_FUNC) &_BC_RiskOnsetCPF, 10},
    {"_BC_RiskOnsetPDF", (DL_FUNC) &_BC_RiskOnsetPDF, 10},
    {"_BC_RiskSympt", (DL_FUNC) &_BC_RiskSympt, 10},
    {"_BC_f_SensScreen", (DL_FUNC) &_BC_f_SensScreen, 10},
    {"_BC_SensScreen", (DL_FUNC) &_BC_SensScreen, 10},
    {"_BC_f_RiskScreen", (DL_FUNC) &_BC_f_RiskScreen, 9},
    {"_BC_f_RiskScreen_odg", (DL_FUNC) &_BC_f_RiskScreen_odg, 9},
    {"_BC_f_CaseIntegral4", (DL_FUNC) &_BC_f_CaseIntegral4, 9},
    {"_BC_f_CensIntegral4", (DL_FUNC) &_BC_f_CensIntegral4, 10},
    {"_BC_f_ScreenCase4", (DL_FUNC) &_BC_f_ScreenCase4, 9},
    {"_BC_f_SymptCase4", (DL_FUNC) &_BC_f_SymptCase4, 9},
    {"_BC_f_CensCase4", (DL_FUNC) &_BC_f_CensCase4, 10},
    {"_BC_IndL4", (DL_FUNC) &_BC_IndL4, 16},
    {"_BC_f_SizeBounded", (DL_FUNC) &_BC_f_SizeBounded, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_BC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
