# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title EvalCaseIntegral
#' @description Evaluate the integral for BC cases
#' @export
EvalCaseIntegral <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_EvalCaseIntegral', PACKAGE = 'BCNatHist', age, v, scr, par, t, t_wts, d0, v0)
}

#' @title EvalCensIntegral
#' @description Evaluate the double integral for censored
#' @export
EvalCensIntegral <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_EvalCensIntegral', PACKAGE = 'BCNatHist', age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

#' @title CalcScreenCase
#' @description Calculate the joint likelihood of a single screen-detected case
#' @export
CalcScreenCase <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_CalcScreenCase', PACKAGE = 'BCNatHist', age, v, scr, par, t_pts, t_wts, d0, v0)
}

#' @title CalcSymptCase
#' @description Calculate the joint likelihood of a single symptomatic case
#' @export
CalcSymptCase <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_CalcSymptCase', PACKAGE = 'BCNatHist', age, v, scr, par, t_pts, t_wts, d0, v0)
}

#' @title CalcCensCase
#' @description Calculate the joint likelihood of a single censored
#' @export
CalcCensCase <- function(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_CalcCensCase', PACKAGE = 'BCNatHist', age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

#' @title IndL
#' @description Determine case and mode status, and calculate the corresponding joint likelihood
#' @export
IndL <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_IndL', PACKAGE = 'BCNatHist', is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_CaseIntegral_odg <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_f_CaseIntegral_odg', PACKAGE = 'BCNatHist', age, v, scr, par, t, t_wts, d0, v0)
}

f_CensIntegral_odg <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_f_CensIntegral_odg', PACKAGE = 'BCNatHist', age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_ScreenCase_odg <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_f_ScreenCase_odg', PACKAGE = 'BCNatHist', age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_SymptCase_odg <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_f_SymptCase_odg', PACKAGE = 'BCNatHist', age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_CensCase_odg <- function(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_f_CensCase_odg', PACKAGE = 'BCNatHist', age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

IndL_odg <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call('_BCNatHist_IndL_odg', PACKAGE = 'BCNatHist', is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

