# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_ScreenSizeInterval <- function(age, v_cut, scr, par, t, t_wts, v, v_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_ScreenSizeInterval`, age, v_cut, scr, par, t, t_wts, v, v_wts, d0, v0)
}

f_SymptSizeInterval <- function(age, v_cut, scr, par, t, t_wts, v, v_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SymptSizeInterval`, age, v_cut, scr, par, t, t_wts, v, v_wts, d0, v0)
}

f_CaseIntegral <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CaseIntegral`, age, v, scr, par, t, t_wts, d0, v0)
}

f_CensIntegral <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensIntegral`, age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_ScreenCase <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_ScreenCase`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_SymptCase <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SymptCase`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_CensCase <- function(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensCase`, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

IndL <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_IndL`, is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_CaseIntegral_odg <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CaseIntegral_odg`, age, v, scr, par, t, t_wts, d0, v0)
}

f_CensIntegral_odg <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensIntegral_odg`, age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_ScreenCase_odg <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_ScreenCase_odg`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_SymptCase_odg <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SymptCase_odg`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_CensCase_odg <- function(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensCase_odg`, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

IndL_odg <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_IndL_odg`, is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_CaseIntegral2 <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CaseIntegral2`, age, v, scr, par, t, t_wts, d0, v0)
}

f_CensIntegral2 <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensIntegral2`, age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_ScreenCase2 <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_ScreenCase2`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_SymptCase2 <- function(age, v, scr, par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SymptCase2`, age, v, scr, par, t_pts, t_wts, d0, v0)
}

f_CensCase2 <- function(age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensCase2`, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

IndL2 <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_IndL2`, is_case, is_scr, age, v, scr, entry, e_scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

CondOnset <- function(age, v, scr, par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_CondOnset`, age, v, scr, par, t, t_wts, d0, v0)
}

f_pMVK <- function(t, A, B, delta) {
    .Call(`_BC_f_pMVK`, t, A, B, delta)
}

f_dMVK <- function(t, A, B, delta) {
    .Call(`_BC_f_dMVK`, t, A, B, delta)
}

RiskOnsetCPF <- function(t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_RiskOnsetCPF`, t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

RiskOnsetPDF <- function(t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_RiskOnsetPDF`, t, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

RiskSympt <- function(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_RiskSympt`, x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_SensScreen <- function(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SensScreen`, x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

SensScreen <- function(x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_SensScreen`, x, age, scr, par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_RiskScreen <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_RiskScreen`, age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_RiskScreen_odg <- function(age, scr, par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_RiskScreen_odg`, age, scr, par, t, t_wts, r, r_wts, d0, v0)
}

f_CaseIntegral4 <- function(age, v, scr, par, scr_par, t, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CaseIntegral4`, age, v, scr, par, scr_par, t, t_wts, d0, v0)
}

f_CensIntegral4 <- function(age, scr, par, scr_par, t, t_wts, r, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensIntegral4`, age, scr, par, scr_par, t, t_wts, r, r_wts, d0, v0)
}

f_ScreenCase4 <- function(age, v, scr, par, scr_par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_ScreenCase4`, age, v, scr, par, scr_par, t_pts, t_wts, d0, v0)
}

f_SymptCase4 <- function(age, v, scr, par, scr_par, t_pts, t_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SymptCase4`, age, v, scr, par, scr_par, t_pts, t_wts, d0, v0)
}

f_CensCase4 <- function(age, scr, par, scr_par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_CensCase4`, age, scr, par, scr_par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

IndL4 <- function(is_case, is_scr, age, v, scr, entry, e_scr, par, scr_par, e_scr_par, t_pts, t_wts, r_pts, r_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_IndL4`, is_case, is_scr, age, v, scr, entry, e_scr, par, scr_par, e_scr_par, t_pts, t_wts, r_pts, r_wts, d0, v0)
}

f_SizeBounded <- function(x, v, c, s, scr, par, gk_pts, gk_wts, gl_pts, gl_wts, d0 = 0.5, v0 = 0.06544985) {
    .Call(`_BC_f_SizeBounded`, x, v, c, s, scr, par, gk_pts, gk_wts, gl_pts, gl_wts, d0, v0)
}

